[phases.setup]
nixPkgs = ['maven', 'jdk17']

[phases.build]
cmds = ['cd medicine-ecommerce-backend && mvn clean package -DskipTests']

[start]
cmd = 'cd medicine-ecommerce-backend && java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar target/medicine-ecommerce-1.0.0.jar'
